version: '3.8'

services:
  tr-3-front:
    image: node:23-bookworm-slim
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./vue/vuetify-project:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 5173:5173
    links:
      - tr-3-back-principal

  tr-3-back-principal:
    build:
      dockerfile: ./back/principal/dev.Dockerfile
      context: .
    command: sh -c "cp .env.DEV .env && npm install && npm run dev"
    volumes:
      - ./back/principal:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 4000:4000
    links:
      - tr-3-mysql
    depends_on:
      - tr-3-mysql

  tr-3-back-odoo:
    build:
      dockerfile: ./back/odoo/dev.Dockerfile
      context: .
    command: sh -c "cp .env.DEV .env && npm install && npm run dev"
    volumes:
      - ./back/odoo:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 4001:4001  

  tr-3-mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game
    volumes:
      - mysql-db:/var/lib/mysql:rw
    ports:
      - 3306:3306

  tr-3-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: tr-3-mysql
    depends_on:
      - tr-3-mysql

  tr-3-portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  tr-3-odoo:
    image: odoo:17
    depends_on:
      - tr-3-odoo-db
    ports:
      - 8069:8069
    environment:
      - HOST=tr-3-odoo-db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-data:/var/lib/odoo
      - ./back/odoo/odooFiles/addons:/mnt/extra-addons
      - ./back/odoo/odooFiles/config:/etc/odoo

  tr-3-odoo-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  tr-3-pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - tr-3-odoo-db
    volumes:
      - pgadmin-data:/var/lib/pgadmin4

volumes:
  mysql-db:
  data:
  odoo-db-data:
  odoo-data:
  pgadmin-data: