services:
  tr-3-front:
    image: node:23-bookworm-slim
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./vue/vuetify-project:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 5173:5173
    links:
      - tr-3-back

  tr-3-back:
    build:
      dockerfile: ./back/dev.Dockerfile
      context: .
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./back:/usr/src/app
      - ./db/sql:/usr/src/app/db/sql
    working_dir: /usr/src/app
    ports:
      - 4000:4000
    links:
      - tr-3-mysql
    depends_on:
      - tr-3-mysql      
  tr-3-mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game
    volumes:
      - mysql-db:/var/lib/mysql:rw
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: tr-3-mysql
    depends_on:
      - tr-3-mysql

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  mysql-db:
  data: