CREATE TABLE usuaris (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    army JSON NOT NULL,
    victories INT DEFAULT 0,
    defeats INT DEFAULT 0
);
