CREATE TABLE USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ELO INT DEFAULT 1000,
    VICTORIES INT DEFAULT 0,
    DEFEATS INT DEFAULT 0,
    ARMYID INT,
    FOREIGN KEY (ARMYID) REFERENCES ARMY(ID) ON DELETE SET NULL
);

CREATE TABLE CHARACTERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    WEAPON ENUM('SWORD', 'SPEAR', 'AXE', 'BOW', 'MAGIC') NOT NULL,
    SWORD FLOAT,
    SPEAR FLOAT,
    AXE FLOAT,
    BOW FLOAT,
    MAGIC FLOAT,
    WINGED BOOLEAN DEFAULT FALSE,
    SPRITE VARCHAR(255),
    ATK INT NOT NULL,
    MOVEMENT INT NOT NULL,
    HEALTH INT NOT NULL
);

CREATE TABLE ARMYS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERID INT UNIQUE,
    CHARACTER1 INT,
    CHARACTER2 INT,
    CHARACTER3 INT,
    CHARACTER4 INT,
    FOREIGN KEY (USERID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (CHARACTER1) REFERENCES CHARACTER(ID) ON DELETE SET NULL,
    FOREIGN KEY (CHARACTER2) REFERENCES CHARACTER(ID) ON DELETE SET NULL,
    FOREIGN KEY (CHARACTER3) REFERENCES CHARACTER(ID) ON DELETE SET NULL,
    FOREIGN KEY (CHARACTER4) REFERENCES CHARACTER(ID) ON DELETE SET NULL
);